FROM node:18-alpine AS build

WORKDIR /app

ARG APP_VERSION=v2

COPY ./frontend/${APP_VERSION}/package.json ./frontend/${APP_VERSION}/package-lock.json* ./

RUN npm install

COPY ./frontend/${APP_VERSION} ./

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

RUN npm run build

FROM node:18-alpine

WORKDIR /app

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/.next ./.next
COPY --from=build /app/package.json ./
COPY --from=build /app/public ./public

EXPOSE 3000

ENV NODE_ENV=production
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

CMD ["npm", "run", "start"]