# Use an official Node.js runtime as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available) from the `app` folder
COPY ./frontend/app/package.json ./frontend/app/package-lock.json* ./

# Install dependencies
RUN npm install

# Copy the rest of the application code from the `app` folder
COPY ./frontend/app ./

# Expose the port Next.js will run on
EXPOSE 3000

# Set the environment variable to tell Next.js to run in production mode
ENV NODE_ENV=production

# Build the Next.js application
# RUN npm run build

# Start the Next.js application
CMD ["npm", "run", "dev"]
