version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: openetl-backend
    networks:
      - openetl-network
    ports:
      - "5009:5009"
    env_file:
      - .env

    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: openetl-frontend
    networks:
      - openetl-network
    ports:
      - "8500:8500"
    environment:
      - BACKEND_HOST=http://openetl-backend:5009
      - OPENETL_HOME=/app
    depends_on:
      - backend
    restart: always

networks:
  openetl-network:
    driver: bridge
