version: '3.8'

x-airflow-common: &airflow-common
  environment:
    - AIRFLOW_HOME=/opt/airflow
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgresql/airflow
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    - OPENETL_HOME=/app
    - OPENETL_DOCUMENT_HOST=postgresql
    - OPENETL_DOCUMENT_PORT=5432
    - OPENETL_DOCUMENT_USER=airflow
    - OPENETL_DOCUMENT_PASS=airflow
    - OPENETL_DOCUMENT_DB=airflow
    - OPENETL_DOCUMENT_ENGINE=PostgreSQL
  volumes:
    - /Users/rusab1/docker/airflow_openetl/dags:/opt/airflow/dags
    - /Users/rusab1/docker/airflow_openetl/logs:/opt/airflow/logs
    - .:/app

services:
  streamlit-openetl:
    <<: *airflow-common
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
    volumes:
      - .:/app
      - /Users/rusab1/docker/airflow_openetl:/opt/airflow

  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - /Users/rusab1/docker/pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  airflow-webserver:
    <<: *airflow-common
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "postgresql"
      - "airflow-scheduler"
      - "airflow-init"
    command: airflow webserver

  airflow-scheduler:
    <<: *airflow-common
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "airflow-init"
      - "postgresql"
    command: airflow scheduler
    restart: always

  airflow-init:
    <<: *airflow-common
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "postgresql"
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create -r Admin -u admin -e admin@example.com -f Admin -l User -p admin && exit"
