version: '3'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
    volumes:
      - .:/app
    environment:
      - OPENETL_HOME=/app
      - OPENETL_DOCUMENT_HOST=postgresql
      - OPENETL_DOCUMENT_PORT=5432
      - OPENETL_DOCUMENT_USER=airflow
      - OPENETL_DOCUMENT_PASS=airflow
      - OPENETL_DOCUMENT_DB=airflow
      - OPENETL_DOCUMENT_ENGINE=PostgreSQL

  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - /Users/rusab1/docker/pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  airflow-webserver:
    image: apache/airflow:2.8.4
    ports:
      - "8080:8080"
    depends_on:
      - "postgresql"
      - "airflow-scheduler"
      - "airflow-init"
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgresql/airflow
    volumes:
      - /Users/rusab1/docker/logs:/usr/local/airflow/logs
      - /Users/rusab1/docker/dags:/usr/local/airflow/dags
    command: airflow webserver

  airflow-scheduler:
    image: apache/airflow:2.8.4
    depends_on:
      - "airflow-init"
      - "postgresql"
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgresql/airflow
    volumes:
      - /Users/rusab1/docker/logs:/usr/local/airflow/logs
      - /Users/rusab1/docker/dags:/usr/local/airflow/dags
    command: airflow scheduler

  airflow-init:
    image: apache/airflow:2.8.4
    depends_on:
      - "postgresql"
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create -r Admin -u admin -e admin@example.com -f Admin -l User -p admin && exit"
    environment:
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgresql/airflow
