# Use Python 3.10 slim image as base
FROM python:3.12-slim

# Set working directory in the container
WORKDIR /app

# Copy backend app code
COPY ./backend /app

# Copy connectors folder
COPY ./connectors /app/connectors

COPY ./utils /app/utils

# Backend Dependencies
RUN pip install --no-cache-dir --use-feature=fast-deps -r requirements_backend.txt


# Expose the port for FastAPI
EXPOSE 5009

# Command to run the backend server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5009"]
