# Use Python 3.10 slim image as base
FROM python:3.12-slim

# Set working directory in the container
WORKDIR /app

# Copy frontend app code
COPY ./frontend /app

COPY ./utils /app/utils
# Frontend Dependencies
RUN pip install --no-cache-dir -r requirements_frontend.txt

# Expose the port for Streamlit
EXPOSE 8500

# Command to run the Streamlit app
CMD ["streamlit", "run", "main.py", "--server.port=8500", "--server.address=0.0.0.0"]
