sqlalchemy_database_engines = {
    'MySQL': 'mysql+pymysql',
    'PostgreSQL': 'postgresql+psycopg2',
    'SQLite': 'sqlite',
    'Oracle': 'oracle+cx_oracle',
    'Microsoft SQL Server': 'mssql+pymssql',
    'Firebird': 'firebird',
    'Sybase': 'sybase',
    'Informix': 'informix',
    'Microsoft Access': 'access',
    'IBM DB2': 'ibm_db_sa',
    'Drizzle': 'drizzle',
    'SQL Anywhere': 'sqlany',
    'SAP HANA': 'hana',
    'MaxDB': 'maxdb',
    'SAP DB': 'sapdb',
    'HSQLDB': 'hsqldb',
    'SQLCipher': 'sqlcipher',
    'Teradata': 'teradata',
    'Presto': 'presto',
    'Snowflake': 'snowflake',
    'Amazon Redshift': 'redshift',
    'CockroachDB': 'cockroachdb',
    'MonetDB': 'monetdb',
    'Vertica': 'vertica',
    'Cubrid': 'cubrid',
    'Crate': 'crate',
    'Altibase': 'altibase',
    'OmniSci': 'omnisci',
    'ClickHouse': 'clickhouse',
    'MongoDB': 'mongo',
    'Amazon DocumentDB': 'documentdb',
    'DynamoDB': 'dynamodb',
    'Google Cloud Spanner': 'google',
    'Amazon Timestream': 'timestream',
    'Trino': 'trino',
    'Google BigQuery': 'bigquery',
    'MariaDB': 'mysql',
    'Exasol': 'exasol',
    'Netezza': 'netezza',
    'Greenplum': 'greenplum',
    'Kdb+': 'kdb+',
    'Solr': 'solr',
    'Nexus': 'nexus',
    'Cassandra': 'cassandra',
    'OpenTSDB': 'opentsdb',
    'Azure Cosmos DB': 'cosmosdb',
    'Google Bigtable': 'bigtable',
    'Apache HBase': 'hbase',
    'Apache Accumulo': 'accumulo',
    'MemSQL': 'memsql',
    'Amazon Athena': 'athena',
    'Amazon S3': 's3',
    'AWS Glue': 'glue',
    'Elasticsearch': 'elasticsearch',
    'Azure Data Explorer (Kusto)': 'kusto',
    'Google Firebase': 'firebase',
    'Microsoft Azure Cosmos DB': 'cosmosdb',
    'Apache Hadoop HDFS': 'hdfs',
    'Microsoft Azure Data Lake Storage': 'adl',
    'Apache Phoenix': 'phoenix',
    'Apache Ignite': 'ignite',
    'Apache Geode': 'geode',
    'GridGain': 'gridgain',
    'Google Firestore': 'firestore',
    'MongoDB Atlas': 'atlas',
    'Google Cloud Datastore': 'datastore'
}

jdbc_database_engines = {
    'MySQL': 'mysql:mysql-connector-java:8.0.0',
    'PostgreSQL': 'org.postgresql:postgresql:42.2.0',
    'SQLite': 'org.xerial:sqlite-jdbc:3.34.0',
    'Oracle': 'com.oracle.database.jdbc:ojdbc8:19.8.0.0',
    'Microsoft SQL Server': 'com.microsoft.sqlserver:mssql-jdbc:9.4.0.jre11',
    'Firebird': 'org.firebirdsql.jdbc:jaybird-jdk18:3.0.11',
    'Sybase': 'com.sybase.jdbc4:jconn4:7.07',
    'Informix': 'com.ibm.informix:jdbc:4.50.4.0',
    'Microsoft Access': 'net.ucanaccess:ucanaccess:5.0.0',
    'IBM DB2': 'com.ibm.db2:jcc:11.5.0.0',
    'Drizzle': 'org.drizzle.jdbc:drizzle-jdbc:1.3',
    'SQL Anywhere': 'sap.com.sybase.sqlanywhere:SAPSQLAnywhere:16.0.0.2798',
    'SAP HANA': 'com.sap.db.jdbc:sapdbc:10.0.23',
    'MaxDB': 'com.sap.db.jdbc:ngdbc:7.7.09',
    'SAP DB': 'com.sap.db.jdbc:ngdbc:7.7.09',
    'HSQLDB': 'org.hsqldb:hsqldb:2.5.2',
    'SQLCipher': 'net.zetetic:android-database-sqlcipher:4.4.0',
    'Teradata': 'com.teradata.jdbc:teradata-driver:17.10.0.10',
    'Presto': 'com.facebook.presto:presto-jdbc:0.257',
    'Snowflake': 'net.snowflake:snowflake-jdbc:3.13.0',
    'Amazon Redshift': 'com.amazon.redshift:redshift-jdbc42-no-awssdk:1.2.54.1059',
    'CockroachDB': 'org.postgresql:postgresql:42.2.23.jre7',
    'MonetDB': 'nl.cwi.monetdb:monetdb-jdbc:2.42.1',
    'Vertica': 'com.vertica.jdbc:vertica-jdbc:10.1.1',
    'Cubrid': 'cubrid.jdbc:cubrid-jdbc:10.2.2.1007',
    'Crate': 'io.crate:crate-jdbc:4.6.2',
    'Altibase': 'Altibase:Altibase-jdbc:7.1.0',
    'OmniSci': 'com.omnisci.jdbc:omnisci-jdbc:5.8.1',
    'ClickHouse': 'ru.yandex.clickhouse:clickhouse-jdbc:0.3.0',
    'MongoDB': 'org.mongodb:mongodb-driver-sync:4.4.2',
    'Amazon DocumentDB': 'org.mongodb:mongodb-driver-sync:4.4.2',
    'DynamoDB': 'software.amazon.awssdk:ddb-local:1.17.0',
    'Google Cloud Spanner': 'com.google.cloud:google-cloud-spanner:2.8.0',
    'Amazon Timestream': 'com.amazonaws:aws-java-sdk-timestreamquery:1.12.95',
    'Trino': 'io.trino:trino-jdbc:363',
    'Google BigQuery': 'com.google.cloud:google-cloud-bigquery:2.1.1',
    'MariaDB': 'org.mariadb.jdbc:mariadb-java-client:2.7.3',
    'Exasol': 'com.exasol:exasol-jdbc:7.1.0',
    'Netezza': 'org.netezza:nzjdbc:7.2.0.6',
    'Greenplum': 'org.postgresql:postgresql:42.2.23.jre7',
    'Kdb+': 'com.kx:jdbc:3.1.8',
    'Solr': 'com.lucidworks.spark:lucidworks-spark:3.2.0',
    'Nexus': 'org.sonatype.nexus:nexus-core:3.30.0',
    'Cassandra': 'com.datastax.oss:java-driver-core:4.11.0',
    'OpenTSDB': 'net.opentsdb:opentsdb:2.5.2',
    'Azure Cosmos DB': 'com.microsoft.azure:azure-cosmosdb-spark_3-1_2-12:4.2.0',
    'Google Bigtable': 'com.google.cloud.bigtable:bigtable-hbase-2.x-hadoop:1.16.0',
    'Apache HBase': 'org.apache.hbase:hbase-client:2.4.8',
    'Apache Accumulo': 'org.apache.accumulo:accumulo-core:2.0.1',
    'MemSQL': 'com.memsql:memsql-connector:3.1.0',
    'Amazon Athena': 'software.amazon.athena.jdbc:athena-jdbc:2.2.0',
    'Amazon S3': 'software.amazon.awssdk:s3:2.16.58',
    'AWS Glue': 'software.amazon.awssdk:aws-glue-datacatalog-client:2.16.58',
    'Elasticsearch': 'org.elasticsearch.client:elasticsearch-rest-client:7.15.0',
    'Azure Data Explorer (Kusto)': 'com.microsoft.azure.kusto:kusto-ingest:2.2.3',
    'Google Firebase': 'com.google.firebase:firebase-admin:8.1.0',
    'Microsoft Azure Cosmos DB': 'com.microsoft.azure:azure-cosmosdb-spark_3-1_2-12:4.2.0',
    'Apache Hadoop HDFS': 'org.apache.hadoop:hadoop-hdfs:3.3.1',
    'Microsoft Azure Data Lake Storage': 'com.microsoft.azure:azure-storage:8.6.6',
    'Apache Phoenix': 'org.apache.phoenix:phoenix-core:5.5.4',
    'Apache Ignite': 'org.apache.ignite:ignite-core:2.11.0',
    'Apache Geode': 'org.apache.geode:geode-core:1.15.1',
    'GridGain': 'org.apache.ignite:ignite-core:2.11.0',
    'Google Firestore': 'com.google.firebase:firebase-admin:8.1.0',
    'MongoDB Atlas': 'org.mongodb:mongodb-driver-sync:4.4.2',
    'Google Cloud Datastore': 'com.google.cloud:google-cloud-datastore:2.4.0'
}
