name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Verify tag is on release/docker branch
        run: |
          TAG_COMMIT=$(git rev-list -n 1 $GITHUB_REF)
          BRANCH=$(git branch -r --contains $TAG_COMMIT | grep origin/release/docker || true)
          if [ -z "$BRANCH" ]; then
            echo "Tag is not on release/docker branch. Exiting."
            exit 1
          fi

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image with tags
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/openetl:${VERSION} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/openetl:${VERSION} ${{ secrets.DOCKER_USERNAME }}/openetl:latest

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/openetl:${VERSION}
          docker push ${{ secrets.DOCKER_USERNAME }}/openetl:latest

      - name: Update Docker Hub README
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/openetl
          readme-filepath: ./README.md
