on:
    workflow_run:
      workflows: ["Sync Repositories"]
      types:
        - completed  

jobs:
    sync:
      runs-on: ubuntu-latest
  
      steps:
      - name: Download Repository Artifact
        uses: actions/download-artifact@v2
        with:
          name: repository-artifact
  
      - name: Checkout Target Repository
        uses: actions/checkout@v2
  
      - name: Sync Changes
        run: |
          cp -r ${{ github.workspace }}/repository-artifact/* .
  
      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Sync changes from source repository"
          git push
  