name: Sync to OpenETL Pro

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out OpenETL Pro repository
        uses: actions/checkout@v4
        with:
          repository: RusabKhan/OpenETL-Pro
          path: OpenETL-Pro
          ref: sync
          token: ${{ secrets.WORKFLOW }}

      - name: Copy changes from OpenETL to OpenETL Pro
        run: |
          cp -R ./* OpenETL-Pro/ 

        working-directory: ${{ github.workspace }}/OpenETL     
          
      - name: Push changes to develop branch of OpenETL Pro
        run: |
          cd OpenETL-Pro
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions Bot"
          git add .
          git commit -m "Sync changes from main branch of OpenETL"
          git push origin develop