name: Sync to OpenETL Pro

on:
  push:
    branches:
      - actions

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out OpenETL Pro repository
        uses: actions/checkout@v2
        with:
          repository: RusabKhan/OpenETL-Pro
          path: OpenETL-Pro

      - name: Push changes to develop branch of OpenETL Pro
        run: |
          cd OpenETL-Pro
          git config --global user.email "rusabkhan7@gmail.com"
          git config --global user.name "Rusab Khan"
          git checkout develop
          git pull origin develop
          cp -R ../. .

          git add .
          git commit -m "Sync changes from main branch of OpenETL"
          git push origin develop
