[theme]
primaryColor="#4f46e5"
backgroundColor="#ffffff"
secondaryBackgroundColor="#e5e5e5"
textColor="#6b7280"
font="sans serif"
fontSize = 9

[browser]
showDeployButton = false
showSidebar = true

[server]
port = 8500
enableCORS = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[layout]
wideMode = true