[theme]
primaryColor="#2f2f9b"
backgroundColor="#e5e5e5"
secondaryBackgroundColor="#c4c6ca"
textColor="#262730"
font="sans serif"
fontSize = 9

[server]
port = 8500
enableCORS = true
wideMode = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"